export const cafeSeedData = [
  {
    slug: "pixel-forge-arena",
    name: "Pixel Forge Arena",
    neighborhood: "Koramangala",
    city: "Bengaluru",
    address: "5th Block, Koramangala, Bengaluru",
    description:
      "A competitive PC arena with high-refresh setups, team bays, and weekday tactical shooter ladders.",
    rating: 4.9,
    reviewCount: 386,
    pricePerHour: 180,
    openUntil: "1:00 AM",
    seatsAvailable: 12,
    totalSeats: 48,
    featuredGames: ["Valorant", "Counter-Strike 2", "Apex Legends"],
    amenities: ["High-refresh PCs", "Tournament nights", "Food service"],
    crowdLevel: "Busy",
    heroTone: "from-emerald-500 via-zinc-950 to-sky-500",
    imageUrl:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "checkpoint-social",
    name: "Checkpoint Social",
    neighborhood: "Indiranagar",
    city: "Bengaluru",
    address: "100 Feet Road, Indiranagar, Bengaluru",
    description:
      "Console couches, co-op tables, and a calmer social floor for long weekend party sessions.",
    rating: 4.8,
    reviewCount: 271,
    pricePerHour: 150,
    openUntil: "12:30 AM",
    seatsAvailable: 9,
    totalSeats: 32,
    featuredGames: ["EA FC 26", "Tekken 8", "Mortal Kombat 1"],
    amenities: ["Console pods", "Board games", "Food service"],
    crowdLevel: "Balanced",
    heroTone: "from-sky-500 via-zinc-950 to-rose-500",
    imageUrl:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "respawn-lounge",
    name: "Respawn Lounge",
    neighborhood: "HSR Layout",
    city: "Bengaluru",
    address: "Sector 6, HSR Layout, Bengaluru",
    description:
      "Private rooms, streamer booths, and reliable peripherals for squads that like a quieter setup.",
    rating: 4.7,
    reviewCount: 198,
    pricePerHour: 220,
    openUntil: "2:00 AM",
    seatsAvailable: 5,
    totalSeats: 28,
    featuredGames: ["Dota 2", "League of Legends", "Minecraft"],
    amenities: ["Private rooms", "Streaming booths", "High-refresh PCs"],
    crowdLevel: "Quiet",
    heroTone: "from-rose-500 via-zinc-950 to-amber-400",
    imageUrl:
      "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "mana-bar",
    name: "Mana Bar",
    neighborhood: "Church Street",
    city: "Bengaluru",
    address: "Church Street, Ashok Nagar, Bengaluru",
    description:
      "A downtown gaming cafe with balanced PC, console, and tabletop zones for mixed groups.",
    rating: 4.6,
    reviewCount: 154,
    pricePerHour: 170,
    openUntil: "11:45 PM",
    seatsAvailable: 16,
    totalSeats: 40,
    featuredGames: ["Overwatch 2", "Rocket League", "Catan"],
    amenities: ["Console pods", "Board games", "Food service"],
    crowdLevel: "Balanced",
    heroTone: "from-violet-500 via-zinc-950 to-emerald-500",
    imageUrl:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "lag-free-lab",
    name: "Lag Free Lab",
    neighborhood: "Whitefield",
    city: "Bengaluru",
    address: "ITPL Main Road, Whitefield, Bengaluru",
    description:
      "Low-latency rigs, coaching support, and a practical layout for serious practice blocks.",
    rating: 4.8,
    reviewCount: 229,
    pricePerHour: 200,
    openUntil: "1:30 AM",
    seatsAvailable: 7,
    totalSeats: 36,
    featuredGames: ["Valorant", "Fortnite", "Counter-Strike 2"],
    amenities: ["High-refresh PCs", "Coaching desk", "Tournament nights"],
    crowdLevel: "Busy",
    heroTone: "from-cyan-500 via-zinc-950 to-lime-400",
    imageUrl:
      "https://images.unsplash.com/photo-1603481546238-487240415921?auto=format&fit=crop&w=900&q=80",
  },
  {
    slug: "arcade-atlas",
    name: "Arcade Atlas",
    neighborhood: "Jayanagar",
    city: "Bengaluru",
    address: "4th Block, Jayanagar, Bengaluru",
    description:
      "Retro arcade walls, current-gen consoles, and friendly staff for casual drop-in sessions.",
    rating: 4.5,
    reviewCount: 132,
    pricePerHour: 130,
    openUntil: "10:30 PM",
    seatsAvailable: 18,
    totalSeats: 30,
    featuredGames: ["Street Fighter 6", "Mario Kart", "Tekken 8"],
    amenities: ["Console pods", "Board games", "Food service"],
    crowdLevel: "Quiet",
    heroTone: "from-orange-500 via-zinc-950 to-fuchsia-500",
    imageUrl:
      "https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=80",
  },
] as const;

export const reviewSeedData = [
  {
    slug: "pixel-forge-valorant-bay",
    cafeName: "Pixel Forge Arena",
    gameTitle: "Valorant",
    authorName: "Anika Rao",
    authorInitials: "AR",
    rating: 5,
    category: "setup",
    title: "Five-stack setup was ready on time",
    comment:
      "Every machine had matching peripherals, the monitors were tuned well, and the staff already knew our booking notes.",
    visitedAt: "2026-07-02",
    helpfulCount: 42,
    tags: ["High-refresh PCs", "Team bay", "Valorant"],
  },
  {
    slug: "checkpoint-tekken-night",
    cafeName: "Checkpoint Social",
    gameTitle: "Tekken 8",
    authorName: "Dev Mehta",
    authorInitials: "DM",
    rating: 4.8,
    category: "crowd",
    title: "Great console crowd without chaos",
    comment:
      "The console pods were clean, matches rotated quickly, and the room stayed social without getting too loud.",
    visitedAt: "2026-06-24",
    helpfulCount: 31,
    tags: ["Console pods", "Tekken 8", "Balanced crowd"],
  },
  {
    slug: "respawn-private-dota",
    cafeName: "Respawn Lounge",
    gameTitle: "Dota 2",
    authorName: "Nikhil Shah",
    authorInitials: "NS",
    rating: 4.7,
    category: "setup",
    title: "Private room made the session calmer",
    comment:
      "Good chairs, quieter audio, and enough privacy for team calls between games. The booth lighting was a bonus.",
    visitedAt: "2026-06-18",
    helpfulCount: 26,
    tags: ["Private rooms", "Dota 2", "Streaming booths"],
  },
  {
    slug: "mana-bar-mixed-group",
    cafeName: "Mana Bar",
    gameTitle: "Rocket League",
    authorName: "Ira Sen",
    authorInitials: "IS",
    rating: 4.5,
    category: "food",
    title: "Easy pick for mixed groups",
    comment:
      "Half our group played Rocket League while the rest grabbed board games. Food came quickly and the staff managed both zones well.",
    visitedAt: "2026-06-08",
    helpfulCount: 19,
    tags: ["Board games", "Food service", "Rocket League"],
  },
  {
    slug: "lag-free-lab-practice",
    cafeName: "Lag Free Lab",
    gameTitle: "Counter-Strike 2",
    authorName: "Kabir Jain",
    authorInitials: "KJ",
    rating: 4.9,
    category: "staff",
    title: "Practice block felt professionally run",
    comment:
      "The network was stable, staff helped swap a mouse immediately, and the coaching desk gave useful demo review notes.",
    visitedAt: "2026-05-30",
    helpfulCount: 37,
    tags: ["Low latency", "Coaching desk", "Counter-Strike 2"],
  },
  {
    slug: "arcade-atlas-street-fighter",
    cafeName: "Arcade Atlas",
    gameTitle: "Street Fighter 6",
    authorName: "Maya Dsouza",
    authorInitials: "MD",
    rating: 4.4,
    category: "crowd",
    title: "Friendly brackets and clean controllers",
    comment:
      "The regulars were welcoming, the controllers were in good shape, and short brackets kept the night moving.",
    visitedAt: "2026-05-19",
    helpfulCount: 14,
    tags: ["Arcade", "Street Fighter 6", "Controllers"],
  },
  {
    slug: "pixel-forge-apex",
    cafeName: "Pixel Forge Arena",
    gameTitle: "Apex Legends",
    authorName: "Rhea Kapoor",
    authorInitials: "RK",
    rating: 4.6,
    category: "setup",
    title: "Smooth frames during peak hours",
    comment:
      "We played during the busiest slot and still had smooth frames, quick staff help, and enough room for backpacks.",
    visitedAt: "2026-05-11",
    helpfulCount: 22,
    tags: ["Apex Legends", "Peak hours", "PC setup"],
  },
  {
    slug: "checkpoint-ea-fc",
    cafeName: "Checkpoint Social",
    gameTitle: "EA FC 26",
    authorName: "Arjun Pillai",
    authorInitials: "AP",
    rating: 4.3,
    category: "food",
    title: "Solid couch session with quick snacks",
    comment:
      "Controllers were charged, snacks landed fast, and the screen placement worked well for a four-player session.",
    visitedAt: "2026-04-28",
    helpfulCount: 11,
    tags: ["EA FC 26", "Snacks", "Console pods"],
  },
] as const;

export const gameSeedData = [
  {
    slug: "valorant",
    title: "Valorant",
    subtitle: "Tactical FPS",
    description:
      "Fast local queues, tournament nights, and strong cafe availability across competitive PC venues.",
    rating: 4.8,
    tags: ["5v5", "Competitive", "PC"],
    popularity: 100,
  },
  {
    slug: "tekken-8",
    title: "Tekken 8",
    subtitle: "Fighting",
    description:
      "Popular for console pods, weekend brackets, and quick pickup matches with cafe regulars.",
    rating: 4.6,
    tags: ["Console", "Fighting", "Tournaments"],
    popularity: 84,
  },
  {
    slug: "ea-fc-26",
    title: "EA FC 26",
    subtitle: "Sports",
    description:
      "A favorite for groups looking for couch competition and relaxed cafe sessions.",
    rating: 4.4,
    tags: ["Console", "Sports", "Co-op"],
    popularity: 79,
  },
  {
    slug: "street-fighter-6",
    title: "Street Fighter 6",
    subtitle: "Fighting",
    description:
      "Strong fit for arcade-style cafes, quick sets, and casual tournament nights.",
    rating: 4.7,
    tags: ["Arcade", "Console", "Fighting"],
    popularity: 68,
  },
] as const;
